# Services commonly found with UNAUTHORIZED ACCESS
FINDINGS = {
    # Databases - No Auth/Default Configs
    "Elasticsearch": {
        "port": 9200,
        "name": "Unauthenticated REST API",
        "severity": "High",
        "description": "Exposed REST API allows unauthorized access.",
        "remediation": "Restrict access, enable x-pack security.",
        "cve": "CVE-2015-5531",
    },
    "MongoDB": {
        "port": 27017,
        "name": "Default Unauthenticated Access",
        "severity": "High",
        "description": "Default installation allows unauthenticated DB access.",
        "remediation": "Enable authentication and IP binding.",
        "cve": "CVE-2017-15135",
    },
    "Redis": {
        "port": 6379,
        "name": "No Password by Default",
        "severity": "High",
        "description": "No password by default allows control over DB.",
        "remediation": "Configure `requirepass` and bind to localhost.",
        "cve": None,
    },
    "Memcached": {
        "port": 11211,
        "name": "Exposed Cache Vulnerability",
        "severity": "High",
        "description": "Exposed cache allows arbitrary memory dump.",
        "remediation": "Use firewall or bind to localhost.",
        "cve": "CVE-2018-1000115",
    },
    "CouchDB": {
        "port": 5984,
        "severity": "High",
        "name": "Unauthenticated HTTP Interface",
        "description": "CouchDB exposes an HTTP interface that allows access without authentication by default.",
        "remediation": "Enable authentication and restrict access to the CouchDB HTTP interface using proper user credentials and firewall rules.",
        "cve": "CVE-2017-12635",
    },
    "Cassandra": {
        "port": 9042,
        "name": "Open Database Default Config",
        "severity": "High",
        "description": "Cassandra uses default settings that allow unrestricted access.",
        "remediation": "Change default configs and enable authentication.",
        "cve": None,
    },
    "RethinkDB": {
        "port": 8080,
        "name": "Exposed Admin UI",
        "severity": "High",
        "description": "The RethinkDB admin web UI is publicly accessible without restrictions.",
        "remediation": "Restrict access to the admin UI via authentication or network controls.",
        "cve": None,
    },
    "InfluxDB": {
        "port": 8086,
        "name": "Unauthenticated Time Series DB",
        "severity": "High",
        "description": "InfluxDB allows access without requiring login, risking data exposure.",
        "remediation": "Enable authentication and HTTPS.",
        "cve": "CVE-2019-20933",
    },
    # Infrastructure - Default/No Auth
    "Docker API": {
        "port": 2375,
        "severity": "Critical",
        "name": "Remote Code Execution via Exposed API",
        "description": "Remote code execution possible over HTTP.",
        "remediation": "Use TLS and bind to localhost.",
        "cve": "CVE-2019-5736",
    },
    "Docker Registry": {
        "port": 5000,
        "severity": "High",
        "name": "Unauthenticated Container Registry",
        "description": "Docker Registry is accessible without authentication, allowing unauthorized push/pull of images.",
        "remediation": "Enable authentication and restrict access to the registry.",
        "cve": None,
    },
    "Kubernetes API": {
        "port": 8080,
        "severity": "Critical",
        "name": "Insecure API Server Port Exposed",
        "description": "The Kubernetes API server exposes an unsecured port, allowing unauthenticated access.",
        "remediation": "Disable or firewall the insecure port and enforce secure authentication on the API server.",
        "cve": "CVE-2020-8559",
    },
    "Kubernetes Dashboard": {
        "port": 9090,
        "severity": "High",
        "name": "Exposed Web UI without Authentication",
        "description": "Kubernetes Dashboard is accessible without login, risking cluster control by attackers.",
        "remediation": "Enable authentication and restrict Dashboard access via network policies.",
        "cve": None,
    },
    "Consul": {
        "port": 8500,
        "severity": "High",
        "name": "Full Key-Value Access by Default",
        "description": "Default configuration allows full KV access.",
        "remediation": "Enable ACLs and restrict access.",
        "cve": None,
    },
    "Etcd": {
        "port": 2379,
        "severity": "High",
        "name": "Exposed Key-Value Database",
        "description": "Exposed key-value DB, no ACL.",
        "remediation": "Enable authentication and access control.",
        "cve": "CVE-2021-28235",
    },
    "Zookeeper": {
        "port": 2181,
        "severity": "High",
        "name": "Unauthenticated Root Access",
        "description": "Zookeeper allows root-level access without authentication, risking full system control.",
        "remediation": "Enable authentication and restrict network access to trusted hosts only.",
        "cve": "CVE-2019-0201",
    },
    # Web Applications - Default Creds/No Auth
    "Jenkins": {
        "port": 8080,
        "severity": "High",
        "name": "Script Execution via Open Dashboard",
        "description": "Jenkins dashboard is open without authentication, allowing attackers to run arbitrary scripts.",
        "remediation": "Enable authentication and restrict dashboard access to trusted users only.",
        "cve": "CVE-2019-1003000",
    },
    "SonarQube": {
        "port": 9000,
        "severity": "High",
        "name": "Tokens and Project Info Exposed",
        "description": "Tokens and project info accessible without login.",
        "remediation": "Require authentication and rotate tokens.",
        "cve": "CVE-2020-27986",
    },
    "Kibana": {
        "port": 5601,
        "severity": "High",
        "name": "Unauthenticated Frontend Exposing Data",
        "description": "Kibana’s frontend is accessible without login, exposing sensitive data dashboards.",
        "remediation": "Add x-pack or reverse proxy with login.",
        "cve": "CVE-2019-7609",
    },
    "Grafana": {
        "port": 3000,
        "severity": "Medium",
        "name": "Default Admin Credentials",
        "description": "Grafana ships with default admin username and password, risking unauthorized access.",
        "remediation": "Change default credentials immediately after installation.",
        "cve": "CVE-2019-15043",
    },
    "GitLab": {
        "port": 80,
        "severity": "High",
        "name": "Exposed Web with No Login",
        "description": "GitLab web exposed with no login required.",
        "remediation": "Restrict access and enforce login.",
        "cve": "CVE-2021-22205",
    },
    "PhpMyAdmin": {
        "port": 80,
        "severity": "High",
        "name": "Exposed DB Management UI",
        "description": "Exposed DB management UI.",
        "remediation": "Restrict IPs and enable login.",
        "cve": "CVE-2009-1151",
    },
    "Jupyter Notebook": {
        "port": 8888,
        "severity": "Critical",
        "name": "Remote Code Execution via Browser",
        "description": "Unsecured Jupyter Notebook allows anyone with browser access to run arbitrary code remotely.",
        "remediation": "Enable authentication and restrict network access to trusted users only.",
        "cve": "CVE-2018-20460",
    },
    "Apache Tomcat Manager": {
        "port": 8080,
        "severity": "High",
        "name": "Default Tomcat Manager Credentials",
        "description": "Manager app with default tomcat/tomcat creds.",
        "remediation": "Change default passwords, restrict access.",
        "cve": "CVE-2020-1938",
    },
    "WebLogic Console": {
        "port": 7001,
        "severity": "Critical",
        "name": "Unauthenticated Admin Console Access",
        "description": "Unauthenticated access to admin console.",
        "remediation": "Enable login and patch regularly.",
        "cve": "CVE-2020-14882",
    },
    "Sonatype Nexus": {
        "port": 8081,
        "severity": "High",
        "name": "Exposed Admin Panel",
        "description": "Nexus admin panel is accessible without proper authentication, risking full control over repositories.",
        "remediation": "Enable authentication and limit access.",
        "cve": "CVE-2020-10199",
    },
    "Rundeck": {
        "port": 4440,
        "severity": "High",
        "name": "Exposed Web GUI",
        "description": "Rundeck’s web interface is publicly accessible without authentication, risking unauthorized job execution.",
        "remediation": "Enable ACLs and login access.",
        "cve": "CVE-2020-25310",
    },
    "Portainer": {
        "port": 9000,
        "severity": "High",
        "name": "Unauthenticated Docker Management UI",
        "description": "Portainer’s management interface is accessible without login, allowing control over Docker environments.",
        "remediation": "Enable authentication.",
        "cve": None,
    },
    "cAdvisor": {
        "port": 8080,
        "severity": "Medium",
        "name": "Publicly Exposed Container Monitoring",
        "description": "Container monitoring exposed publicly.",
        "remediation": "Restrict access or disable.",
        "cve": None,
    },
    # Message Queues - Default Auth
    "RabbitMQ": {
        "port": 15672,
        "severity": "High",
        "name": "Exposed Dashboard with Default Credentials",
        "description": "Exposed dashboard with guest/guest login.",
        "remediation": "Delete guest user or use firewall rules.",
        "cve": None,
    },
    "Apache Kafka": {
        "port": 9092,
        "severity": "High",
        "name": "Unauthenticated Kafka Broker",
        "description": "Kafka broker without authentication.",
        "remediation": "Enable SASL authentication.",
        "cve": None,
    },
    "Apache ActiveMQ": {
        "port": 8161,
        "severity": "High",
        "name": "Web Console with Default Credentials",
        "description": "Web console with admin/admin creds.",
        "remediation": "Change default credentials.",
        "cve": "CVE-2016-3088",
    },
    # Monitoring - No Auth
    "Prometheus": {
        "port": 9090,
        "severity": "Medium",
        "name": "Publicly Exposed Metrics",
        "description": "Metrics exposed publicly with no login.",
        "remediation": "Use reverse proxy with auth or firewall.",
        "cve": None,
    },
    "Node Exporter": {
        "port": 9100,
        "severity": "Medium",
        "name": "Exposed System Metrics",
        "description": "System metrics exposed without auth.",
        "remediation": "Restrict access with firewall.",
        "cve": None,
    },
    "Alertmanager": {
        "port": 9093,
        "severity": "Medium",
        "name": "Unauthenticated Alert Management",
        "description": "Alert management without auth.",
        "remediation": "Enable authentication.",
        "cve": None,
    },
    "Splunk": {
        "port": 8000,
        "severity": "Medium",
        "name": "Default Admin Credentials",
        "description": "Splunk web with admin/changeme creds.",
        "remediation": "Change default admin password.",
        "cve": "CVE-2020-1427",
    },
    # Network Services - Anonymous Access
    "FTP Anonymous": {
        "port": 21,
        "severity": "Medium",
        "name": "Anonymous File Access via FTP",
        "description": "Allows anonymous file access.",
        "remediation": "Disable anonymous login.",
        "cve": None,
    },
    "Telnet": {
        "port": 23,
        "severity": "High",
        "name": "No Encryption or Authentication",
        "description": "No encryption or authentication used.",
        "remediation": "Disable and use SSH instead.",
        "cve": None,
    },
    "TFTP": {
        "port": 69,
        "severity": "Medium",
        "name": "No Credentials for Upload/Download",
        "description": "No credentials for upload/download.",
        "remediation": "Disable or firewall access.",
        "cve": None,
    },
    "SNMP": {
        "port": 161,
        "severity": "Medium",
        "name": "Community Strings Exposed",
        "description": "Community strings public/private exposed.",
        "remediation": "Use SNMPv3 with strong auth.",
        "cve": "CVE-2017-6736",
    },
    "LDAP Anonymous": {
        "port": 389,
        "severity": "Medium",
        "name": "Anonymous Bind Information Leak",
        "description": "Anonymous bind may leak directory structure.",
        "remediation": "Require authenticated bind for all queries.",
        "cve": "CVE-2017-8563",
    },
    "SMB Guest": {
        "port": 445,
        "severity": "High",
        "name": "Guest Access Enabled",
        "description": "Guest access enabled, allows file Browse.",
        "remediation": "Disable guest shares, use strong ACLs.",
        "cve": "CVE-2020-0796",
    },
    "NFS Open": {
        "port": 2049,
        "severity": "High",
        "name": "Unrestricted Directory Exports",
        "description": "Exports directories without restriction.",
        "remediation": "Use IP filtering and root_squash.",
        "cve": None,
    },
    "Rsync": {
        "port": 873,
        "severity": "High",
        "name": "Exposed Rsync Module",
        "description": "Rsync exposed without module restrictions.",
        "remediation": "Disable anonymous modules or use auth.",
        "cve": None,
    },
    "VNC No Auth": {
        "port": 5900,
        "severity": "High",
        "name": "VNC Server with No Password",
        "description": "VNC server with no password.",
        "remediation": "Set strong password, use encryption.",
        "cve": "CVE-2019-15681",
    },
    # Web Exposures - Common Misconfigurations
    "Directory Listing": {
        "port": 80,
        "severity": "Medium",
        "name": "Enabled Directory Listing",
        "description": "Directory listing enabled on HTTP server.",
        "remediation": "Disable autoindex in web server config.",
        "cve": None,
    },
    "Git Repository": {
        "port": 80,
        "severity": "High",
        "name": "Exposed Git Repository",
        "description": "Git repository exposed via web (.git/).",
        "remediation": "Remove .git directory from web root.",
        "cve": None,
    },
    "SVN Repository": {
        "port": 3690,
        "severity": "High",
        "name": "Unauthenticated SVN Repository Access",
        "description": "SVN repository accessible without auth.",
        "remediation": "Enable authentication for SVN.",
        "cve": None,
    },
    "Swagger UI": {
        "port": 80,
        "severity": "Medium",
        "name": "Publicly Exposed API Documentation",
        "description": "API documentation exposed publicly.",
        "remediation": "Restrict access to documentation.",
        "cve": None,
    },
    "phpinfo()": {
        "port": 80,
        "severity": "Medium",
        "name": "PHP Configuration Exposed",
        "description": "PHP configuration exposed via phpinfo().",
        "remediation": "Remove phpinfo() files.",
        "cve": None,
    },
    "Server Status": {
        "port": 80,
        "severity": "Low",
        "name": "Exposed Server Status Page",
        "description": "Apache server-status page exposed.",
        "remediation": "Disable server-status or restrict access.",
        "cve": None,
    },
    "Backup Files": {
        "port": 80,
        "severity": "Medium",
        "name": "Accessible Backup Files",
        "description": "Backup files accessible via web (.bak, .sql).",
        "remediation": "Remove backup files from web directory.",
        "cve": None,
    },
    "Config Files": {
        "port": 80,
        "severity": "High",
        "name": "Exposed Configuration Files",
        "description": "Configuration files exposed (.env, config.php).",
        "remediation": "Secure configuration files.",
        "cve": None,
    },
}

# Enhanced banner patterns for better service identification
BANNER_PATTERNS = {
    # Databases
    "Elasticsearch": [
        r'"cluster_name"',
        r'"tagline".*"You Know, for Search"',
        r"elasticsearch",
    ],
    "MongoDB": [r"MongoDB", r"db version", r"wire version"],
    "Redis": [r"\+PONG", r"Redis server", r"-NOAUTH"],
    "CouchDB": [r'"couchdb":', r'"welcome":', r'"version":'],
    "Cassandra": [r"Cassandra", r"Invalid or unsupported protocol version"],
    "InfluxDB": [r'"X-Influxdb-Version"', r"influxdb"],
    # Web Applications
    "Jenkins": [r"Jenkins", r"X-Jenkins:", r"hudson"],
    "SonarQube": [r"SonarQube", r"sonar"],
    "Kibana": [r'"name":"kibana"', r"kbn-name", r"kibana"],
    "Grafana": [r'"title":"Grafana"', r"grafana"],
    "GitLab": [r"GitLab", r"gitlab"],
    "PhpMyAdmin": [r"phpMyAdmin", r"pma_"],
    "Jupyter": [r"jupyter", r"IPython", r"notebook"],
    "Tomcat": [r"Apache-Coyote", r"Tomcat", r"tomcat"],
    "WebLogic": [r"WebLogic", r"oracle"],
    "Nexus": [r"Nexus", r"sonatype"],
    "Rundeck": [r"Rundeck", r"rundeck"],
    "Portainer": [r"Portainer", r"portainer"],
    # Infrastructure
    "Docker": [r'"ApiVersion"', r"docker"],
    "Consul": [r'"Config":', r"consul"],
    "Etcd": [r'"etcdserver"', r"etcd"],
    "Zookeeper": [r"Zookeeper version", r"Environment:"],
    "Kubernetes": [r'"major":', r'"minor":', r"kubernetes"],
    # Message Queues
    "RabbitMQ": [r"RabbitMQ", r"rabbit"],
    "ActiveMQ": [r"ActiveMQ", r"activemq"],
    # Monitoring
    "Prometheus": [r"Prometheus", r"prometheus"],
    "Splunk": [r"Splunk", r"splunkd"],
    # Network Services
    "FTP": [r"220.*FTP", r"vsFTPd", r"ProFTPD", r"FileZilla"],
    "Telnet": [r"login:", r"Username:", r"Welcome to"],
    "SNMP": [r"SNMP", r"public", r"private"],
    "VNC": [r"RFB ", r"VNC server"],
    # Web Server Responses
    "Apache": [r"Apache/", r"Server: Apache"],
    "Nginx": [r"nginx/", r"Server: nginx"],
    "IIS": [r"Microsoft-IIS", r"Server: Microsoft-IIS"],
}

# Web paths to check for unauthorized access
WEB_PATHS = {
    "Jenkins": ["/", "/script", "/manage"],
    "SonarQube": ["/", "/api/system/status", "/api/authentication/login"],
    "Kibana": ["/", "/app/kibana", "/status"],
    "Grafana": ["/", "/login", "/api/health"],
    "GitLab": ["/", "/users/sign_in", "/api/v4/projects"],
    "PhpMyAdmin": ["/", "/index.php", "/setup/"],
    "Jupyter": ["/", "/tree", "/api"],
    "Tomcat": ["/", "/manager/html", "/manager/text"],
    "WebLogic": ["/", "/console", "/console/login/LoginForm.jsp"],
    "Nexus": ["/", "/#browse/browse", "/service/rest/v1/status"],
    "Rundeck": ["/", "/menu/home", "/api/14/system/info"],
    "Portainer": ["/", "/#/auth_scan", "/api/status"],
    "RabbitMQ": ["/", "/api/overview", "/#/"],
    "Prometheus": ["/", "/graph", "/targets"],
    "Splunk": ["/", "/en-US/account/login", "/services/server/info"],
    "Directory Listing": ["/", "/files/", "/backup/", "/admin/"],
    "Git Repository": ["/.git/", "/.git/config", "/.git/HEAD"],
    "Swagger UI": ["/swagger-ui/", "/swagger/", "/api-docs/"],
    "phpinfo()": ["/phpinfo.php", "/info.php", "/test.php"],
    "Server Status": ["/server-status", "/server-info"],
    "Backup Files": ["/backup.sql", "/db.sql", "/config.bak"],
}
