from typing import List

from pydantic import BaseModel, Field

from app.models.application_config import Application
from app.models.port_config import Port
from app.models.smb_enumeration_config import SmbEnumeration
from app.models.source_target_config import SourceTarget
from app.models.technology_config import Technology
from app.models.vulnerability_config import Vulnerability


class Host(BaseModel):
    """
    Represents a single IP discovered during the scanning process.
    This model will accumulate all information about the host throughout different scan phases.
    """

    source_targets: List[SourceTarget] = Field(
        default_factory=list,
        description="List of original targets (IP, domain, URL) that resolved to this IP address.",
    )

    ip_address: str = Field(..., description="The IP address of the host.")

    is_alive: bool = Field(
        default=False,
        description="True if the host was found to be alive during discovery.",
    )

    associated_applications: List[Application] = Field(
        default_factory=list,
        description="List of applications associated with this host. If the target is domain or url, this will contain the main application.",
    )

    # --- Basic Port/Service Information ---
    ports: List[Port] = Field(
        default_factory=list, description="List of open TCP ports found on the host."
    )

    # --- Technologies (from Wappalyzer) ---
    technologies: List[Technology] = Field(
        default_factory=list, description="List of identified technologies"
    )

    # --- Vulnerabilities (from Afrog) ---
    vulnerabilities: List[Vulnerability] = Field(
        default_factory=list, description="List of vulnerabilities."
    )

    smb_enumeration_data: List[SmbEnumeration] = Field(
        default=None,
        description="Detailed SMB enumeration findings (shares, users, groups, policies, etc.).",
    )

    # services: List[Dict[str, Any]] = Field(
    #     [],
    #     description="List of discovered services on ports, e.g., [{'port': 80, 'name': 'http', 'version': 'nginx 1.20'}]"
    # )

    #
    # # --- Vulnerabilities / Findings (from Nuclei, Afrog, NullLinux, AI-generated NSE) ---
    # findings: List[Dict[str, Any]] = Field(
    #     [],
    #     description="List of discovered vulnerabilities or security findings, e.g., [{'tool': 'nuclei', 'name': 'Admin Panel Found', 'severity': 'high', 'details': '...'}]"
    # )
    #
    # # --- AI-related data ---
    # ai_nse_scripts_generated: List[str] = Field(
    #     [],
    #     description="List of NSE script names generated by AI for this host."
    # )
    # ai_validation_results: List[Dict[str, Any]] = Field(
    #     [],
    #     description="Results from running AI-generated NSE scripts."
    # )
    #
    # # --- Other metadata ---
    # mac_address: Optional[str] = Field(None, description="MAC address if discovered (primarily for local networks).")
    # # Add other fields as needed, e.g., os_detection, hostname, etc.

    # Need hash for set
    def __hash__(self):
        return hash(self.ip_address)
