from typing import List  # , Optional, Dict, Any

from pydantic import BaseModel, Field


class Host(BaseModel):
    """
    Represents a single host/asset discovered during the scanning process.
    This model will accumulate all information about the host throughout different scan phases.
    """

    ip_address: str = Field(..., description="The IP address of the host.")
    is_alive: bool = Field(
        False, description="True if the host was found to be alive during discovery."
    )
    # status: str = Field(..., description="The status of the host.")

    # --- Basic Port/Service Information (from RustScan/Nmap) ---
    ports: List[int] | None = Field(
        [], description="List of open TCP ports found on the host."
    )

    # TODO: fields must be not required!
    # services: List[Dict[str, Any]] = Field(
    #     [],
    #     description="List of discovered services on ports, e.g., [{'port': 80, 'name': 'http', 'version': 'nginx 1.20'}]"
    # )
    #
    # # --- Technologies (from Wappalyzer) ---
    # technologies: List[Dict[str, Any]] = Field(
    #     [],
    #     description="List of identified technologies, e.g., [{'name': 'Nginx', 'version': '1.20', 'category': 'Web Servers'}]"
    # )
    #
    # # --- Vulnerabilities / Findings (from Nuclei, Afrog, NullLinux, AI-generated NSE) ---
    # findings: List[Dict[str, Any]] = Field(
    #     [],
    #     description="List of discovered vulnerabilities or security findings, e.g., [{'tool': 'nuclei', 'name': 'Admin Panel Found', 'severity': 'high', 'details': '...'}]"
    # )
    #
    # # --- AI-related data ---
    # ai_nse_scripts_generated: List[str] = Field(
    #     [],
    #     description="List of NSE script names generated by AI for this host."
    # )
    # ai_validation_results: List[Dict[str, Any]] = Field(
    #     [],
    #     description="Results from running AI-generated NSE scripts."
    # )
    #
    # # --- Other metadata ---
    # mac_address: Optional[str] = Field(None, description="MAC address if discovered (primarily for local networks).")
    # # Add other fields as needed, e.g., os_detection, hostname, etc.
