from pathlib import Path
from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from app.models.system_config import SystemName


class ScanConfig(BaseModel):
    """
    All configuration parameters.
    """

    target: List[str] = Field(
        ..., description="List of target specifications (IPs, CIDRs, ranges)."
    )
    verbose: bool = Field(..., description="Enable verbose logging (DEBUG level).")

    ai_provider: Optional[Literal["openai", "anthropic"]] = Field(
        None, description="Specify the AI provider to use."
    )
    ai_model: Optional[str] = Field(None, description="Specify the AI model to use.")
    ai_api_key: Optional[str] = Field(None, description="API key for the AI service.")
    ai_no_cache: bool = Field(..., description="Disable AI response caching.")
    ai_limit_nse: int = Field(
        3,
        ge=0,
        description="Limit the number of NSE scripts generated by AI per asset (0 for no limit).",
    )

    disable_nuclei: bool = Field(
        ..., description="Disable Nuclei vulnerability scanning."
    )
    disable_afrog: bool = Field(
        ..., description="Disable Afrog open database scanning."
    )

    report_format: Literal["json", "pdf"] = Field(
        ..., description="Specify the output report format."
    )
    report_base_dir: Path = Field(
        ..., description="Base directory for saving scan reports."
    )
    report_file: Path = Field(..., description="File for saving scan reports.")
    report_zip: bool = Field(
        ..., description="Pack the report-related files into a ZIP archive."
    )

    system_name: SystemName = Field(...,
                                    description="Detect the system name.")
