import argparse

from app.core.paths import REPORT_PATH
from app.core.constants import APP_NAME


async def init_args() -> argparse.Namespace:
    """
    Initializes and parses command-line arguments.
    """
    parser = argparse.ArgumentParser(
        description=f"{APP_NAME}: AI-powered vulnerability validation and reporting."
    )

    parser.add_argument(
        "--gui",
        action="store_true",
        help="Run the scanner in Graphical User Interface mode. CLI mode is default.",
    )

    # --- Core Configuration ---
    # parser.add_argument(
    #     "-c", "--config",
    #     type=str,
    #     default=os.path.join(current_dir, 'data', 'config.ini'),  # Default config path
    #     help="Path to the configuration file (e.g., config.ini)."
    # )
    parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="Enable verbose logging (DEBUG level). By default, INFO level is used.",
    )

    # --- Target Specification ---
    # This argument will accept IP addresses (IPv4/IPv6), CIDR ranges, or IP ranges.
    # The application logic will determine the type of target.
    parser.add_argument(
        "target",
        nargs="+",  # Allows one or more targets
        type=str,
        help="One or more target specifications: domain, url, IP v4, IP v4 Range, IP v4 CIDR; IP v6, IP v6 Range, IP v6 CIDR\n"
        "  (e.g., example.com, https://www.example.com, 192.168.1.1, 10.0.0.0/24, 172.16.0.1-172.16.0.255).",
    )

    # --- AI Features Configuration ---
    ai_group = parser.add_argument_group("AI Features Configuration")
    ai_group.add_argument(
        "--ai-provider",
        type=str,
        choices=["openai", "anthropic"],
        help="Specify the AI provider to use (e.g., openai, anthropic, custom-openai, custom-ollama). "
        "Required for AI features.",
    )
    ai_group.add_argument(
        "--ai-model",
        type=str,
        help="Specify the AI model to use (e.g., gpt-4, gpt-3.5-turbo). Required for AI features.",
    )
    ai_group.add_argument(
        "--ai-api-key",
        type=str,
        help="API key for the AI service. Can also be provided via the AI_API_KEY environment variable.",
    )
    ai_group.add_argument(
        "--ai-no-cache",
        action="store_true",
        help="Disable AI response caching. By default, caching is enabled to save costs and speed up scans.",
    )
    ai_group.add_argument(
        "--ai-limit-nse",
        type=int,
        default=3,
        help="Limit the number of Nmap Scripting Engine (NSE) scripts generated by AI per asset. Set to 0 for no limit. (Default: 3).",
    )
    # ai_group.add_argument(
    #     "--ai-cache-remote-url", # Deferred for future implementation
    #     type=str,
    #     help="Remote service URL for AI response caching (optional). Requires additional authentication options."
    # )

    # --- Tools Top-level Configuration ---
    tools_group = parser.add_argument_group("Tool Configuration")
    tools_group.add_argument(
        "--disable-nuclei",
        action="store_true",
        help="Disable Nuclei vulnerability scanning.",
    )
    tools_group.add_argument(
        "--disable-afrog",
        action="store_true",
        help="Disable Afrog open database scanning.",
    )

    # --- Reporting Configuration ---
    report_group = parser.add_argument_group("Reporting Configuration")
    report_group.add_argument(
        "--report-format",
        type=str,
        choices=["json", "pdf"],
        default="json",
        help="Specify the output report format (e.g., json, pdf). Default: json.",
    )
    report_group.add_argument(
        "--report-base-dir",
        type=str,
        default=str(REPORT_PATH),
        help="Base directory for saving scan reports.",
    )
    report_group.add_argument(
        "--report-zip",
        action="store_true",
        help="Pack the report-related files into a ZIP archive after completion.",
    )
    # report_group.add_argument(
    #     "--report-metadata-override-dir", # Deferred for future implementation
    #     type=str,
    #     help="Path to a directory with metadata overrides (e.g., custom report title, description, logos)."
    # )

    return parser.parse_args()
